### ISSUE TITLE
Amazon S3 action - Upload file: Doc mismatch

### ISSUE THREAD

**Issue by tiago-esperanca** [workato/docs#1088]
Amazon S3 Upload Action documentation (https://docs.workato.com/connectors/s3/action-upload-file.html) mentions "Folder" which do not exist on the actual Action input parameters. Also, some names are different (Bucket Region vs Region, Fiel Name vs Object Name etc)

<img width="881" alt="Screenshot 2020-03-12 at 14 59 53" src="https://user-images.githubusercontent.com/50009860/76529626-d329c200-6472-11ea-940d-e6d5d58c8840.png">

Connector Action:
<img width="758" alt="Screenshot 2020-03-12 at 15 46 34" src="https://user-images.githubusercontent.com/50009860/76533650-ad072080-6478-11ea-840f-63a0ae9650d9.png">

**Comment by eeshansim** [comment]
@tiago-esperanca Thanks
@eeliang can you make the doc changes
