### ISSUE TITLE
Writeup Slack dialogs and link from Workbot connector

### ISSUE THREAD

**Issue by huilinn** [workato/docs#282]

**Comment by jandonyada** [comment]
Hey @huilinn can I take this on? Will need a bit of context - hope to ask in person!

**Comment by huilinn** [comment]
Yup, sounds good! Have reassigned

**Comment by jandonyada** [comment]
![image](https://user-images.githubusercontent.com/14304570/37317729-ca026d24-2623-11e8-96d3-b30177863ae9.png)
- To write the content for the dialog hint.
- Link the 'Learn More' to Dialogs doc (to be drafted)

**Comment by jandonyada** [comment]
Closing this as it is a duplicate of https://github.com/workato/issues/issues/6239
