### ISSUE TITLE
MySQL/DB template enhancements

### ISSUE THREAD

**Issue by huilinn** [workato/docs#380]
* [ ] add link to how-to create connection profiles on OPA
* [x] some more basic examples of how to build simple SQL queries on MySQL in the WHERE section, e.g. conventions with double quotes, single quotes, common data types, common operators, or maybe just a link to MySQL syntax docs?
* [x] example recipes for single rows VS batches
* [x] screenshots of the datatree pointing out when an action returns a list VS when an action returns a row
* [ ] screenshots of actual JSON output for list VS rows, and explanation of when we summarize the data (e.g. I think for batches, we don't always show all JSON output?) would be good, but maybe too much

**Comment by eeshansim** [comment]
@huilinn Couple of questions:

> add link to how-to create connection profiles on OPA
when you say add link to how-to create connection profiles, do you mean an additional link that points specifically to the `#create-connection` section? There is currently a like pointing to OPA in general.
