### ISSUE TITLE
List of the supported control types is not complete

### ISSUE THREAD

**Issue by kostos** [workato/docs#418]
http://docs.workato.com/developing-connectors/sdk/object-definition.html#components

We support more control types, at least these:
- `schema-designer`
- `static-list`
- `schema-builder`
- `plain-text`
- `plain-text-area`
- `radio`
- `multiselect`
- `code`
- `date`

**Comment by eeshansim** [comment]
SDK does not support the following types at the moment:
- schema-designer
- schema-builder
- code
