### ISSUE TITLE
Slash commands step number

### ISSUE THREAD

**Issue by eeshansim** [workato/docs#492]
Custom oauth profile steps 3
![image](https://user-images.githubusercontent.com/10286963/40464735-8121b4c4-5f4f-11e8-9deb-75ba56e36d4d.png)

Slash command docs
![image](https://user-images.githubusercontent.com/10286963/40464746-93458798-5f4f-11e8-8674-15ac413f680b.png)

**Comment by jandonyada** [comment]
@eeshansim Ah, this is flow for creating custom OAuth profile, where the first step is to choose an application.

This is not needed when creating a custom bot:
![create custom bot](https://user-images.githubusercontent.com/14304570/40770318-f415e958-64ec-11e8-8bda-64ab4ca10c21.gif)

If you follow the guide, the step number is correct. We can address this when we write a guide specific to custom OAuth profiles.
