### ISSUE TITLE
Docs page styling issue

### ISSUE THREAD

**Issue by eeshan92** [workato/docs#58]
When navigating to specific selector, top part of document body is hidden by book-header
![ynnhrhzxjp](https://cloud.githubusercontent.com/assets/10286963/24688480/c9bfbae4-19f2-11e7-9fde-197d162688dc.gif)

**Comment by huilinn** [comment]
I think Eeshan was just trying to navigate to another page. The header covers the section title whenever we try to link to a page/section in a page

[![https://gyazo.com/413b4e982c98740e578c13ab42824bbd](https://i.gyazo.com/413b4e982c98740e578c13ab42824bbd.gif)](https://gyazo.com/413b4e982c98740e578c13ab42824bbd)
