### ISSUE TITLE
Change internal file names to Workbot for Slack instead of Workbot

### ISSUE THREAD

**Issue by vivek88** [workato/docs#93]
Since we have Workbot for Microsoft Team, it will be good to change our internal file name to Workbot for Slack instead of just Workbot. 

![image](https://cloud.githubusercontent.com/assets/3827991/25549549/1841aa28-2ca5-11e7-9a2b-890ae833a528.png)

**Comment by jandonyada** [comment]
https://github.com/workato/docs/pull/386 better late than never @vivek88

**Comment by jandonyada** [comment]
https://github.com/workato/docs/pull/386 PR closed because changing the internal file names would result in a lot of broken URLs.

Instead, changed the titles to reflect that the docs are wrt Slack e.g. Workbot Troubleshooting **for Slack**

https://github.com/workato/docs/pull/389
