### ISSUE TITLE
Too long delay before the page scrolls back to the top after change

### ISSUE THREAD

**Issue by demeshkin** [workato/docs#984]
1. Go to https://docs.workato.com/security/two-factor-authentication.html
2. Scroll all the way to the bottom of the page
3. Select `IP whitelist` from the menu. You'll see the bottom of the page and after several seconds the page scrolls to the top.

![2019-12-17 09 31 33](https://user-images.githubusercontent.com/522683/70957128-12cd5180-20b0-11ea-805d-c2e5b9cebd0a.gif)

**Comment by th0r** [comment]
That's how VuePress works. If you have any ideas how to fix it feel free to create a PR.

**Comment by demeshkin** [comment]
@th0r What do you think about that? https://github.com/workato/docs/pull/988

**Comment by demeshkin** [comment]
@th0r First navigation is also quite weird.

![2019-12-18 12 01 35](https://user-images.githubusercontent.com/522683/71054854-6dd57600-218e-11ea-8cd0-5f76c739cad5.gif)
